#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : colcon-metadata
Version  : 0.2.2
Release  : 5
URL      : https://files.pythonhosted.org/packages/b8/ed/e15737df4f0553f9e4e322fb299d5bebfe78ef0ac444818a53867ef35486/colcon-metadata-0.2.2.tar.gz
Source0  : https://files.pythonhosted.org/packages/b8/ed/e15737df4f0553f9e4e322fb299d5bebfe78ef0ac444818a53867ef35486/colcon-metadata-0.2.2.tar.gz
Summary  : Extension for colcon to read package metadata from files.
Group    : Development/Tools
License  : Apache-2.0
Requires: colcon-metadata-python = %{version}-%{release}
Requires: colcon-metadata-python3 = %{version}-%{release}
Requires: PyYAML
Requires: colcon-core
BuildRequires : buildreq-distutils3

%description
colcon-metadata
===============
An extension for `colcon-core <https://github.com/colcon/colcon-core>`_ to fetch and manage package metadata from repositories.

%package python
Summary: python components for the colcon-metadata package.
Group: Default
Requires: colcon-metadata-python3 = %{version}-%{release}

%description python
python components for the colcon-metadata package.


%package python3
Summary: python3 components for the colcon-metadata package.
Group: Default
Requires: python3-core

%description python3
python3 components for the colcon-metadata package.


%prep
%setup -q -n colcon-metadata-0.2.2

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
export SOURCE_DATE_EPOCH=1555005087
export MAKEFLAGS=%{?_smp_mflags}
python3 setup.py build

%install
export MAKEFLAGS=%{?_smp_mflags}
rm -rf %{buildroot}
python3 -tt setup.py build  install --root=%{buildroot}
echo ----[ mark ]----
cat %{buildroot}/usr/lib/python3*/site-packages/*/requires.txt || :
echo ----[ mark ]----

%files
%defattr(-,root,root,-)

%files python
%defattr(-,root,root,-)

%files python3
%defattr(-,root,root,-)
/usr/lib/python3*/*
